// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

 const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6a9f6df6-60ae-4eff-ac86-a6bd2d69e5e2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_TOLiKlLWS",
    "aws_user_pools_web_client_id": "lrm59u4pqtrpm8fe5uubvgqh0",
    "oauth": {}
};

export default awsmobile;